# Generated by Django 2.2 on 2021-11-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20211115_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '课程视频', 'verbose_name_plural': '课程视频'},
        ),
    ]
